# Generated by Django 3.2 on 2023-01-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
