# Generated by Django 3.2 on 2023-02-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_App', '0002_alter_item_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('sold', 'sold'), ('soon', 'soon')], max_length=50, null=True),
        ),
    ]
